package org.bian.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.bian.dto.SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceAgreement;
import org.bian.dto.SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceConfigurationSetup;
import org.bian.dto.SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceSubscription;

import javax.validation.Valid;
  
/**
 * SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecord
 */
public class SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecord   {
  private String rewardPointsAwardsAndRedemptionServiceConfigurationSettingReference = null;

  private String rewardPointsAwardsAndRedemptionServiceConfigurationSettingType = null;

  private SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceConfigurationSetup rewardPointsAwardsAndRedemptionServiceConfigurationSetup = null;

  private SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceSubscription rewardPointsAwardsAndRedemptionServiceSubscription = null;

  private SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceAgreement rewardPointsAwardsAndRedemptionServiceAgreement = null;


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::ISO20022andUNCEFACT::Identifier  general-info: Refers to the service configuration parameter for the service 
   * @return rewardPointsAwardsAndRedemptionServiceConfigurationSettingReference
  **/

  public String getRewardPointsAwardsAndRedemptionServiceConfigurationSettingReference() {
    return rewardPointsAwardsAndRedemptionServiceConfigurationSettingReference;
  }

  public void setRewardPointsAwardsAndRedemptionServiceConfigurationSettingReference(String rewardPointsAwardsAndRedemptionServiceConfigurationSettingReference) {
    this.rewardPointsAwardsAndRedemptionServiceConfigurationSettingReference = rewardPointsAwardsAndRedemptionServiceConfigurationSettingReference;
  }


  /**
   * `status: Not Mapped`  core-data-type-reference: BIAN::DataTypesLibrary::CoreDataTypes::UNCEFACT::Text  general-info: The type of service configuration parameter 
   * @return rewardPointsAwardsAndRedemptionServiceConfigurationSettingType
  **/

  public String getRewardPointsAwardsAndRedemptionServiceConfigurationSettingType() {
    return rewardPointsAwardsAndRedemptionServiceConfigurationSettingType;
  }

  public void setRewardPointsAwardsAndRedemptionServiceConfigurationSettingType(String rewardPointsAwardsAndRedemptionServiceConfigurationSettingType) {
    this.rewardPointsAwardsAndRedemptionServiceConfigurationSettingType = rewardPointsAwardsAndRedemptionServiceConfigurationSettingType;
  }


  /**
   * Get rewardPointsAwardsAndRedemptionServiceConfigurationSetup
   * @return rewardPointsAwardsAndRedemptionServiceConfigurationSetup
  **/

  public SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceConfigurationSetup getRewardPointsAwardsAndRedemptionServiceConfigurationSetup() {
    return rewardPointsAwardsAndRedemptionServiceConfigurationSetup;
  }

  public void setRewardPointsAwardsAndRedemptionServiceConfigurationSetup(SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceConfigurationSetup rewardPointsAwardsAndRedemptionServiceConfigurationSetup) {
    this.rewardPointsAwardsAndRedemptionServiceConfigurationSetup = rewardPointsAwardsAndRedemptionServiceConfigurationSetup;
  }


  /**
   * Get rewardPointsAwardsAndRedemptionServiceSubscription
   * @return rewardPointsAwardsAndRedemptionServiceSubscription
  **/

  public SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceSubscription getRewardPointsAwardsAndRedemptionServiceSubscription() {
    return rewardPointsAwardsAndRedemptionServiceSubscription;
  }

  public void setRewardPointsAwardsAndRedemptionServiceSubscription(SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceSubscription rewardPointsAwardsAndRedemptionServiceSubscription) {
    this.rewardPointsAwardsAndRedemptionServiceSubscription = rewardPointsAwardsAndRedemptionServiceSubscription;
  }


  /**
   * Get rewardPointsAwardsAndRedemptionServiceAgreement
   * @return rewardPointsAwardsAndRedemptionServiceAgreement
  **/

  public SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceAgreement getRewardPointsAwardsAndRedemptionServiceAgreement() {
    return rewardPointsAwardsAndRedemptionServiceAgreement;
  }

  public void setRewardPointsAwardsAndRedemptionServiceAgreement(SDRewardPointsAwardsAndRedemptionConfigureInputModelRewardPointsAwardsAndRedemptionServiceConfigurationRecordRewardPointsAwardsAndRedemptionServiceAgreement rewardPointsAwardsAndRedemptionServiceAgreement) {
    this.rewardPointsAwardsAndRedemptionServiceAgreement = rewardPointsAwardsAndRedemptionServiceAgreement;
  }


}

